'use strict';

const fs = require('fs');
const path = require('path');
const crypto = require('crypto');

const DB_DIR = path.resolve(__dirname, '../../database');
const STATE_PATH = path.join(DB_DIR, 'economy.json');
const LEGACY_RPG_PATH = path.join(DB_DIR, 'rpg.json');
const BANK_CONFIG_PATH = path.join(DB_DIR, 'bank_config.json');
// O banco e a economia persistem no mesmo economy.json; compartilham o lock
// para que PIX, depósitos, empréstimos e operações RPG não sobrescrevam dados.
const LOCK_PATH = path.join(DB_DIR, 'economy.lock');

const DEFAULT_CONFIG = {
  version: 1,
  fee: { min: 0.01, max: 0.10, base: 0.01, clientsAtMax: 1000 },
  pix: { minCents: 1, maxCents: 100000000000, cooldownMs: 2000, dailyLimitCents: 100000000000 },
  loans: { multiplier: 10, minCents: 10000, maxCents: 100000000000, maxInstallments: 12, minInstallments: 1, intervalMs: 60000, interestRate: 0.15, insufficientPolicy: 'OVERDUE' }
};
const BANKS = [
  { id: 'nubank', name: 'Nubank', description: 'Banco digital popular', status: 'ACTIVE' },
  { id: 'mercado pago', name: 'Mercado Pago', description: 'Conta digital para o comércio', status: 'ACTIVE' },
  { id: 'inter', name: 'Banco Inter', description: 'Banco digital completo', status: 'ACTIVE' },
  { id: 'brasil', name: 'Banco do Brasil', description: 'Banco tradicional', status: 'ACTIVE' },
  { id: 'bradesco', name: 'Bradesco', description: 'Banco tradicional', status: 'ACTIVE' }
];
const COMMANDS = new Set(['banco','bancos','abrir_conta','selecionar_banco','depositar_banco','sacar_banco','transferir_banco','pix','extrato_bancario','historico_bancario','solicitar_emprestimo','emprestimo','financiamento','parcelas','emprestimos']);

function clone(x) { return JSON.parse(JSON.stringify(x)); }
function ensure() { fs.mkdirSync(DB_DIR, { recursive: true }); }
function read(file, fallback) { ensure(); if (!fs.existsSync(file)) { atomic(file, fallback); return clone(fallback); } try { return JSON.parse(fs.readFileSync(file, 'utf8')); } catch { atomic(file, fallback); return clone(fallback); } }
function atomic(file, value) { ensure(); const tmp = `${file}.${process.pid}.tmp`; fs.writeFileSync(tmp, JSON.stringify(value, null, 2)); fs.renameSync(tmp, file); }
function lock() { ensure(); let fd = null; for (let i = 0; i < 50 && fd === null; i += 1) { try { fd = fs.openSync(LOCK_PATH, 'wx'); } catch (error) { if (error.code === 'EEXIST') { try { const stat = fs.statSync(LOCK_PATH); if (Date.now() - stat.mtimeMs > 120000) fs.rmSync(LOCK_PATH, { force: true }); } catch {} } Atomics.wait(new Int32Array(new SharedArrayBuffer(4)), 0, 0, 5); } } if (fd === null) throw new Error('Sistema bancário ocupado; tente novamente.'); return fd; }
function unlock(fd) { fs.closeSync(fd); try { fs.unlinkSync(LOCK_PATH); } catch {} }
function withLock(fn) { const fd = lock(); try { return fn(); } finally { unlock(fd); } }
function id(prefix) { return `${prefix}_${Date.now()}_${crypto.randomBytes(6).toString('hex')}`; }
function cents(v) { const n = Number(v); return Number.isFinite(n) ? Math.round(n * 100) : 0; }
function amount(v) { const raw = String(v ?? '').replace(/R\$\s?/gi, '').replace(/\./g, '').replace(',', '.'); const n = Number(raw); return Number.isFinite(n) ? n : NaN; }
function money(c) { return (Number(c || 0) / 100).toLocaleString('pt-BR', { minimumFractionDigits: 2, maximumFractionDigits: 2 }); }
function now() { return new Date().toISOString(); }
function cfg() { const saved = read(BANK_CONFIG_PATH, DEFAULT_CONFIG); return { ...clone(DEFAULT_CONFIG), ...saved, fee: { ...DEFAULT_CONFIG.fee, ...(saved.fee || {}) }, pix: { ...DEFAULT_CONFIG.pix, ...(saved.pix || {}) }, loans: { ...DEFAULT_CONFIG.loans, ...(saved.loans || {}) } }; }
function state() { const s = read(STATE_PATH, { players: {} }); s.players ||= {}; s.banks ||= {}; s.bankTransactions ||= []; s.bankAudit ||= []; s.loans ||= {}; s.installments ||= {}; return s; }
function save(s) { atomic(STATE_PATH, s); }
function audit(s, entry) { s.bankAudit.push({ id: id('audit'), at: now(), ...entry }); if (s.bankAudit.length > 20000) s.bankAudit = s.bankAudit.slice(-20000); }
function tx(s, data) { const existing = s.bankTransactions.find((x) => x.idempotencyKey === data.idempotencyKey); if (existing) return existing; const t = { id: id('btx'), status: 'COMPLETED', at: now(), ...data }; s.bankTransactions.push(t); if (s.bankTransactions.length > 50000) s.bankTransactions = s.bankTransactions.slice(-50000); audit(s, { action: 'TRANSACTION', transactionId: t.id, type: t.type, userId: t.senderId || t.userId, amountCents: t.amountCents }); return t; }
function ensureBankData(s) { const conf = cfg(); for (const b of BANKS) { const old = s.banks[b.id] || {}; s.banks[b.id] = { ...b, ...old, clients: Number(old.clients || 0), feeRate: rate(Number(old.clients || 0), conf) }; } for (const p of Object.values(s.players)) { if (p.bank == null) p.bank = 0; if (!p.selectedBank) continue; const b = s.banks[p.selectedBank]; if (b) b.clients = Math.max(0, Number(b.clients || 0)); } return s; }
function rate(clients, conf = cfg()) { const min = Math.max(0, Number(conf.fee.min)); const max = Math.min(0.10, Math.max(min, Number(conf.fee.max))); const base = Math.max(min, Number(conf.fee.base)); const ratio = Math.min(1, Math.max(0, clients / Math.max(1, Number(conf.fee.clientsAtMax)))); return Math.min(0.10, Math.min(max, base + (max - base) * ratio)); }
function findPlayer(s, key) { const q = String(key || '').toLowerCase().trim(); return s.players[key] || Object.values(s.players).find((p) => String(p.id).toLowerCase() === q || String(p.nome || '').toLowerCase() === q || String(p.nome || '').toLowerCase().replace(/\s+/g, '') === q.replace(/\s+/g, '')); }
function ensurePlayer(s, ctx) { let p = s.players[ctx.sender]; if (!p) { const legacy = read(LEGACY_RPG_PATH, []).find((x) => x.id === ctx.sender); p = s.players[ctx.sender] = { id: ctx.sender, nome: legacy?.nome || ctx.pushName || ctx.sender.split('@')[0], cash: Number(legacy?.dinheiro || 0), bank: Number(legacy?.carteiraBanco || 0), assets: [], liabilities: [], history: [], creditScore: 600, legacyImportedAt: now() }; } p.cash = Number(p.cash || 0); p.bank = Number(p.bank || 0); return p; }
function bankFor(s, p, key) { const q = String(key || p.selectedBank || '').toLowerCase().trim(); return Object.values(s.banks).find((b) => b.id === q || b.name.toLowerCase() === q); }
function reply(ctx, text) { return ctx.reply(text); }
function parseTargetAndValue(args) { const parts = [...args]; const v = amount(parts.pop()); return { target: parts.join(' '), value: v }; }
function processDue(s, limit = 200) { const t = Date.now(); let count = 0; const due = Object.values(s.installments).filter((i) => i.status === 'PENDING' && Date.parse(i.dueAt) <= t).sort((a,b) => Date.parse(a.dueAt)-Date.parse(b.dueAt)).slice(0, limit); for (const i of due) { if (i.status !== 'PENDING') continue; const p = s.players[i.userId]; const key = `installment:${i.id}`; if (s.bankTransactions.some((x) => x.idempotencyKey === key)) { i.status = 'PAID'; continue; } if (!p || Number(p.bank || 0) < i.amountCents) { i.status = 'OVERDUE'; audit(s, { action: 'INSTALLMENT_OVERDUE', installmentId: i.id, userId: i.userId }); count += 1; continue; } p.bank = (cents(p.bank) - i.amountCents) / 100; i.status = 'PAID'; i.paidAt = now(); tx(s, { type: 'LOAN_INSTALLMENT', userId: p.id, amountCents: i.amountCents, loanId: i.loanId, installmentId: i.id, idempotencyKey: key }); const loan = s.loans[i.loanId]; if (loan) { loan.paidInstallments += 1; if (loan.paidInstallments >= loan.installments) loan.status = 'PAID'; } count += 1; } return count; }
function listBanks(s) { return Object.values(s.banks).map((b) => `${b.name} — ${b.description}\nClientes: ${b.clients}\nTaxa PIX atual: ${(b.feeRate * 100).toFixed(2)}%\nStatus: ${b.status}`).join('\n\n'); }

function command(ctx) { const c = String(ctx.command || '').toLowerCase(); if (!COMMANDS.has(c)) return false; return withLock(() => { const s = ensureBankData(state()); const p = ensurePlayer(s, ctx); const a = Array.isArray(ctx.args) ? ctx.args : []; const prefix = ctx.prefix || '/'; processDue(s); if (c === 'bancos') { save(s); return reply(ctx, `🏦 *Bancos disponíveis*\n\n${listBanks(s)}`); }
  if (c === 'banco' || c === 'abrir_conta') { const b = bankFor(s, p); save(s); return reply(ctx, `🏦 *Minha conta*\nBanco: ${b?.name || 'não selecionado'}\nSaldo bancário: R$ ${money(cents(p.bank))}\nSaldo em espécie: R$ ${money(cents(p.cash))}\nUse ${prefix}selecionar_banco nome ou código.`); }
  if (c === 'selecionar_banco') { const b = bankFor(s, p, a.join(' ')); if (!b || b.status !== 'ACTIVE') return reply(ctx, 'Banco inválido ou indisponível.'); const old = p.selectedBank; if (old !== b.id) { if (old && s.banks[old]) s.banks[old].clients = Math.max(0, s.banks[old].clients - 1); if (!old) b.clients += 1; p.selectedBank = b.id; } for (const x of Object.values(s.banks)) x.feeRate = rate(x.clients); save(s); return reply(ctx, `✅ Conta vinculada ao ${b.name}. Taxa PIX: ${(b.feeRate * 100).toFixed(2)}%.`); }
  if (c === 'depositar_banco') { const v = amount(a[0]); const n = cents(v); if (!Number.isInteger(n) || n <= 0) return reply(ctx, `Uso: ${prefix}depositar_banco valor`); if (cents(p.cash) < n) return reply(ctx, 'Saldo em espécie insuficiente.'); if (!p.selectedBank) return reply(ctx, 'Selecione um banco primeiro.'); p.cash = (cents(p.cash)-n)/100; p.bank = (cents(p.bank)+n)/100; tx(s, { type: 'DEPOSIT', userId: p.id, bankId: p.selectedBank, amountCents: n, idempotencyKey: `deposit:${p.id}:${Date.now()}` }); save(s); return reply(ctx, `✅ Depósito realizado. Espécie: R$ ${money(cents(p.cash))} | Banco: R$ ${money(cents(p.bank))}.`); }
  if (c === 'sacar_banco') { const v = amount(a[0]); const n = cents(v); if (!Number.isInteger(n) || n <= 0) return reply(ctx, `Uso: ${prefix}sacar_banco valor`); if (cents(p.bank) < n) return reply(ctx, 'Saldo bancário insuficiente.'); p.bank = (cents(p.bank)-n)/100; p.cash = (cents(p.cash)+n)/100; tx(s, { type: 'WITHDRAW', userId: p.id, bankId: p.selectedBank, amountCents: n, idempotencyKey: `withdraw:${p.id}:${Date.now()}` }); save(s); return reply(ctx, `✅ Saque realizado. Espécie: R$ ${money(cents(p.cash))} | Banco: R$ ${money(cents(p.bank))}.`); }
  if (c === 'transferir_banco' || c === 'pix') { const { target, value } = parseTargetAndValue(a); const n = cents(value); const dest = findPlayer(s, target); const b = bankFor(s, p); if (!dest || dest.id === p.id) return reply(ctx, 'Destinatário não encontrado ou inválido.'); if (!b || !p.selectedBank) return reply(ctx, 'Selecione um banco antes da transferência.'); if (!Number.isInteger(n) || n < cfg().pix.minCents || n > cfg().pix.maxCents) return reply(ctx, 'Valor de PIX inválido ou fora do limite.'); const feeRate = Math.min(0.10, Number(b.feeRate)); const fee = Math.round(n * feeRate); const total = n + fee; if (cents(p.bank) < total) return reply(ctx, `Saldo insuficiente. Necessário: R$ ${money(total)}.`); const idem = String(ctx.idempotencyKey || `pix:${p.id}:${dest.id}:${n}:${Date.now()}`); if (s.bankTransactions.some((x) => x.idempotencyKey === idem)) return reply(ctx, 'Esta operação já foi processada.'); p.bank = (cents(p.bank)-total)/100; dest.bank = (cents(dest.bank)+n)/100; tx(s, { type: 'PIX', senderId: p.id, recipientId: dest.id, bankId: b.id, amountCents: n, feeCents: fee, totalDebitedCents: total, idempotencyKey: idem }); audit(s, { action: 'PIX_COMPLETED', senderId: p.id, recipientId: dest.id, amountCents: n, feeCents: fee }); save(s); return reply(ctx, `✅ *PIX realizado com sucesso*\nEnviado: R$ ${money(n)}\nTaxa: R$ ${money(fee)}\nTotal debitado: R$ ${money(total)}\nDestinatário recebeu: R$ ${money(n)}`); }
  if (c === 'extrato_bancario' || c === 'historico_bancario') { const rows = s.bankTransactions.filter((x) => x.userId === p.id || x.senderId === p.id || x.recipientId === p.id).slice(-15).reverse(); save(s); return reply(ctx, `🧾 *Histórico bancário*\n${rows.map((x) => `${x.at.slice(0,16).replace('T',' ')} — ${x.type} — R$ ${money(x.amountCents)} — ${x.status}`).join('\n') || 'Nenhuma movimentação.'}`); }
  if (c === 'emprestimos') { const rows = Object.values(s.loans).filter((x) => x.userId === p.id); save(s); return reply(ctx, `💳 *Empréstimos*\n${rows.map((x) => `${x.id}: R$ ${money(x.totalDueCents)} — ${x.status} — ${x.paidInstallments}/${x.installments} parcelas`).join('\n') || 'Nenhum empréstimo.'}`); }
  if (c === 'parcelas') { const rows = Object.values(s.installments).filter((x) => x.userId === p.id); save(s); return reply(ctx, `📅 *Parcelas*\n${rows.map((x) => `${x.id}: R$ ${money(x.amountCents)} — ${x.status} — vence ${x.dueAt}`).join('\n') || 'Nenhuma parcela.'}`); }
  if (c === 'solicitar_emprestimo' || c === 'emprestimo' || c === 'financiamento') { const v = amount(a[0]); const n = cents(v); const installments = Number(a[1] || 1); const conf = cfg().loans; const base = cents(p.bank) + cents(p.cash); const limit = Math.min(conf.maxCents, base * Number(conf.multiplier)); if (!Number.isInteger(n) || n < conf.minCents || n > limit || n > conf.maxCents) return reply(ctx, `Valor inválido. Limite disponível: R$ ${money(limit)}.`); if (!Number.isInteger(installments) || installments < conf.minInstallments || installments > conf.maxInstallments) return reply(ctx, `Parcelas permitidas: ${conf.minInstallments} a ${conf.maxInstallments}.`); const total = Math.round(n * (1 + Number(conf.interestRate))); const basePart = Math.floor(total / installments); const remainder = total - basePart * installments; const loan = { id: id('loan'), userId: p.id, principalCents: n, interestRate: Number(conf.interestRate), totalDueCents: total, installments, paidInstallments: 0, status: 'ACTIVE', createdAt: now() }; s.loans[loan.id] = loan; for (let k=1;k<=installments;k+=1) { const value = basePart + (k <= remainder ? 1 : 0); const ins = { id: id('inst'), loanId: loan.id, userId: p.id, number: k, amountCents: value, dueAt: new Date(Date.now() + k * Number(conf.intervalMs)).toISOString(), status: 'PENDING' }; s.installments[ins.id] = ins; } p.cash = (cents(p.cash)+n)/100; tx(s, { type: 'LOAN_CREDIT', userId: p.id, amountCents: n, loanId: loan.id, idempotencyKey: `loan:${loan.id}` }); audit(s, { action: 'LOAN_CREATED', loanId: loan.id, userId: p.id, amountCents: n }); save(s); return reply(ctx, `✅ Empréstimo aprovado: R$ ${money(n)}\nTotal a pagar: R$ ${money(total)}\n${installments} parcelas de aproximadamente R$ ${money(Math.round(total/installments))}\nPrimeiro vencimento: em 1 minuto.`); }
  save(s); return false;
}); }
function processDueInstallments() { return withLock(() => { const s = ensureBankData(state()); const n = processDue(s); save(s); return n; }); }
function migrate() { return withLock(() => { const s = ensureBankData(state()); save(s); return { banks: Object.keys(s.banks).length, players: Object.keys(s.players).length }; }); }
function isBankCommand(c) { return COMMANDS.has(String(c || '').toLowerCase()); }
module.exports = { COMMANDS, isBankCommand, handleCommand: command, processDueInstallments, migrate, rate, DEFAULT_CONFIG, BANK_CONFIG_PATH, STATE_PATH };

if (process.env.DISABLE_BANK_WORKER !== '1') { const worker = setInterval(() => { try { processDueInstallments(); } catch (e) { console.error('[BANK] worker:', e.message); } }, 15000); worker.unref(); }
